/**
 * Domains that are never blocked for unpaid devices (DNS + nft destination allowlist).
 * Apex entries cover that host and all subdomains in dnsmasq (`server=/apex/...`).
 *
 * Prefer a real apex (watchduty.org) over a CDN apex (cloudfront.net, amazonaws.com,
 * vercel.app) so unpaid clients do not get the entire internet. Specific CloudFront /
 * S3 / Vercel / Cloud Run hostnames are listed as their full names.
 */
export const PERMANENT_WHITELIST_DOMAINS: readonly string[] = [
  // Venmo
  "venmo.com",
  // Cash App (Block / Square)
  "cash.app",
  "cashapp.com",
  "squareup.com",
  "squarecdn.com",
  "square.com",
  // PayPal
  "paypal.com",
  "paypal.me",
  "paypalobjects.com",
  "braintreegateway.com",
  "braintreepayments.com",
  // Zelle
  "zellepay.com",
  "zelle.com",
  // Camp public site (post-unlock / browse destination + phage secondary pages)
  "thephage.org",
  "drbrainlove.org",
  "flickr.com",
  "staticflickr.com",
  // Burning Man Project + official playa properties (weather / events APIs)
  "burningman.org",
  "burningman.com",
  "blackrockarts.org",
  "blackrockcitycensus.org",
  // Gateway buttons: BMIR live stream + iHeart player/CDN
  "bmir.org",
  "bmir-ice.streamguys.com",
  "bmir-ice.streamguys1.com",
  "iheart.com",
  "ihrhls.com",
  "fontawesome.com",
  // Gateway: Spotify (web player + audio). Specific Akamai/Fastly hosts only —
  // do not open akamaized.net or fastly.net.
  "spotify.com",
  "scdn.co",
  "spotifycdn.com",
  "spotifycdn.net",
  "pscdn.co",
  "spoti.fi",
  "audio-ak-spotify-com.akamaized.net",
  "audio4-ak-spotify-com.akamaized.net",
  "heads-ak-spotify-com.akamaized.net",
  "heads4-ak-spotify-com.akamaized.net",
  "spotify-com.akamaized.net",
  "spotify.com.edgesuite.net",
  "spotify.map.fastly.net",
  "spotify.map.fastlylb.net",
  // Gateway: Watch Duty map
  "watchduty.org",
  "mapbox.com",
  "recurly.com",
  "posthog.com",
  "sentry.io",
  "arcgis.com",
  // Innovate datasets (S3 virtual-host buckets — do not open amazonaws.com)
  "bm-innovate.s3.amazonaws.com",
  "bm-phoenix.s3.amazonaws.com",
  "production-watchduty.s3.amazonaws.com",
  // Watch Duty image/JS CloudFront
  "d1aujrf358n7u7.cloudfront.net",
  "d3q4ticnrym7vg.cloudfront.net",
  "dvxc2n36bnwsr.cloudfront.net",
  "d3e54v103j8qbb.cloudfront.net",
  // Innovate showcase apps (https://innovate.burningman.org/)
  "blackrockcompass.app",
  "dust.events",
  "dust.eo.page",
  "burnermap.com",
  "wannaketchup.com",
  "iburnapp.com",
  "burningmesh.org",
  "navigatetoyes.com",
  "naviguesser.app",
  "playatime.app",
  "yroc.dj",
  "purohit.dev",
  "wkeller.net",
  "justin-klein.com",
  "queerburners.org",
  "theplayaprovides.com",
  "burningmanlockscreen.com",
  "smilehighbrc.org",
  "brclife.vercel.app",
  "brcdomesday.vercel.app",
  "navigatetoplacement.vercel.app",
  "burn-planner.web.app",
  "naviguesser.web.app",
  "chatgpt.com",
  "openai.com",
  "oaistatic.com",
  "garmin.com",
  "github.com",
  "githubassets.com",
  "githubusercontent.com",
  "forms.gle",
  "docs.google.com",
  "soundcloud.com",
  "sndcdn.com",
  // Compass / Naviguesser / BurnerMap backends
  "firebaseapp.com",
  "firebasestorage.app",
  "firebaseio.com",
  "cloudfunctions.net",
  "googleapis.com",
  "gstatic.com",
  "apis.google.com",
  "securetoken.google.com",
  "fvnidtxdfalavveroxmq.supabase.co",
  "compass-events-fzjaqefbta-uc.a.run.app",
  "convert-kml-to-map-points-fzjaqefbta-uc.a.run.app",
  "get-shared-events-fzjaqefbta-uc.a.run.app",
  "v2-compass-events-fzjaqefbta-uc.a.run.app",
  // Squarespace (Burning Mesh), WP/Innovate CDNs, CF challenges
  "squarespace.com",
  "squarespace-cdn.com",
  "sqspcdn.com",
  "typekit.net",
  "createsend.com",
  "createsend1.com",
  "code.jquery.com",
  "unpkg.com",
  "jsdelivr.net",
  "cdnjs.cloudflare.com",
  "challenges.cloudflare.com",
  "website-files.com",
  "zendesk.com",
  "zdassets.com",
  "va.vercel-scripts.com",
  "wp.com",
  "gravatar.com",
  "wordpress.com",
];

/**
 * Extra hostnames resolved for nft IP allowlisting (CDNs / APIs whose A records
 * may differ from the apex). Parent domains above still open DNS for all subs.
 */
export const PERMANENT_WHITELIST_RESOLVE_EXTRA: readonly string[] = [
  "www.venmo.com",
  "api.venmo.com",
  "www.cash.app",
  "api.cash.app",
  "www.paypal.com",
  "www.paypalobjects.com",
  "api.paypal.com",
  "www.zellepay.com",
  "api.zellepay.com",
  "www.thephage.org",
  "www.burningman.org",
  "innovate.burningman.org",
  "playaevents.burningman.org",
  "playaevents.burningman.com",
  "tickets.burningman.org",
  "profiles.burningman.org",
  "journal.burningman.org",
  "eplaya.burningman.org",
  "shop.burningman.org",
  "donate.burningman.org",
  "network.burningman.org",
  "regionals.burningman.org",
  "status.burningman.org",
  "helpticket.burningman.org",
  "gallery.burningman.org",
  "api.burningman.org",
  "spark.burningman.org",
  "help.burningman.org",
  "webassets.burningman.org",
  "marketplace.burningman.org",
  "www.burningman.com",
  "blog.burningman.com",
  // BMIR
  "www.bmir.org",
  "bmir-ice.streamguys.com",
  "bmir-ice.streamguys1.com",
  "stream.revma.ihrhls.com",
  "www.iheart.com",
  "kit.fontawesome.com",
  "ka-f.fontawesome.com",
  // Spotify
  "open.spotify.com",
  "www.spotify.com",
  "accounts.spotify.com",
  "api.spotify.com",
  "apresolve.spotify.com",
  "ap.spotify.com",
  "dealer.spotify.com",
  "spclient.wg.spotify.com",
  "clienttoken.spotify.com",
  "login5.spotify.com",
  "gue1-spclient.spotify.com",
  "gew1-spclient.spotify.com",
  "i.scdn.co",
  "p.scdn.co",
  "mosaic.scdn.co",
  "encore.scdn.co",
  "audio-fa.scdn.co",
  "audio4-fa.scdn.co",
  "seed-mix-image.spotifycdn.com",
  "audio-ak-spotify-com.akamaized.net",
  "audio4-ak-spotify-com.akamaized.net",
  "heads-ak-spotify-com.akamaized.net",
  "heads4-ak-spotify-com.akamaized.net",
  "spotify-com.akamaized.net",
  // Watch Duty
  "www.watchduty.org",
  "app.watchduty.org",
  "api.watchduty.org",
  "images.watchduty.org",
  "maptiles.watchduty.org",
  "vendor-cdn.watchduty.org",
  "share.watchduty.org",
  "support.watchduty.org",
  "api.mapbox.com",
  "apps.mapbox.com",
  "events.mapbox.com",
  "js.recurly.com",
  "api.recurly.com",
  "app.posthog.com",
  "us.i.posthog.com",
  "us.posthog.com",
  "watch-duty.firebaseapp.com",
  "services5.arcgis.com",
  "maps.googleapis.com",
  "fonts.googleapis.com",
  "fonts.gstatic.com",
  "ajax.googleapis.com",
  "identitytoolkit.googleapis.com",
  "securetoken.googleapis.com",
  "firestore.googleapis.com",
  "firebase.googleapis.com",
  "www.gstatic.com",
  "cdn.prod.website-files.com",
  // Innovate apps
  "www.burningmesh.org",
  "docs.burningmesh.org",
  "assets.squarespace.com",
  "static1.squarespace.com",
  "images.squarespace-cdn.com",
  "file.squarespace-cdn.com",
  "definitions.sqspcdn.com",
  "use.typekit.net",
  "p.typekit.net",
  "www.navigatetoyes.com",
  "placement.navigatetoyes.com",
  "playa.purohit.dev",
  "models.purohit.dev",
  "www.wkeller.net",
  "www.justin-klein.com",
  "blog.queerburners.org",
  "www.theplayaprovides.com",
  "dusty.smilehighbrc.org",
  "www.smilehighbrc.org",
  "apps.garmin.com",
  "www.garmin.com",
  "buringman-playaplay.firebaseapp.com",
  "buringman-playaplay.firebasestorage.app",
  "us-central1-buringman-playaplay.cloudfunctions.net",
  "js.createsend1.com",
  "www.createsend.com",
  "www.soundcloud.com",
  "w.soundcloud.com",
  "github.githubassets.com",
  "raw.githubusercontent.com",
  "cdn.jsdelivr.net",
];

export function permanentWhitelistDnsmasqHostnames(): string[] {
  return [...new Set(PERMANENT_WHITELIST_DOMAINS.map((h) => h.toLowerCase()))].sort();
}

/** All hostnames to A-record resolve for destination allowlisting. */
export function permanentWhitelistResolveHostnames(): string[] {
  const set = new Set<string>();
  for (const h of PERMANENT_WHITELIST_DOMAINS) set.add(h.toLowerCase());
  for (const h of PERMANENT_WHITELIST_RESOLVE_EXTRA) set.add(h.toLowerCase());
  return [...set].sort();
}

export function isPermanentWhitelistHostname(hostname: string): boolean {
  const host = hostname.toLowerCase().replace(/\.$/, "");
  return PERMANENT_WHITELIST_DOMAINS.some(
    (d) => host === d || host.endsWith(`.${d}`),
  );
}
